### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by bryanodonoghue** [matijse/eufy-ha-mqtt-bridge#102]
I repeatedly get this failure.

I've double/triple checked that the login credentials are correct - ensuring I use the same credentials as on the phone.

What is going wrong here ?

`[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[03:05:12] INFO: Exporting log level for nodejs: info
[03:05:12] INFO: Symlinking data dir
[03:05:12] INFO: Running 'eval' commands
[03:05:12] INFO: Generating config.yml from options.json
[03:05:12] INFO: Image build with version 0.2.24
[03:05:12] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
error: Error -- httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-10-18T02:05:16.126Z"}
(node:353) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-10-18T02_05_16_361Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by remyderuysscher** [comment]
I'm getting the same kinds of errors. when I open the URL I get a 404. 

`[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:27:50] INFO: Exporting log level for nodejs: info
[21:27:50] INFO: Symlinking data dir
[21:27:50] INFO: Running 'eval' commands
[21:27:50] INFO: Generating config.yml from options.json
[21:27:50] INFO: Image build with version 0.2.24
[21:27:50] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
error: Error -- httpService.listDevices Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-11-05T20:27:52.677Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-11-05T20:27:57.806Z"}
error: Error -- httpService.registerPushToken Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request. {"stack":"Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.\n    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","timestamp":"2021-11-05T20:27:58.196Z"}`

**Comment by remyderuysscher** [comment]
note to self: RTFM.... When you receive "Failed to request" errors when starting this script, you have logged in too many times and are temporarily blocked. Wait a day and you'll be able to log in again.

Sorry to bother you...

KR Matthijs

**Comment by skrobul** [comment]
> What is going wrong here ?

fwiw, your error is for `127.0.0.1:1883` which presumably means your MQTT broker is not running or can't be reached

**Comment by matijse** [comment]
Both errors shows "Failed to request" which means you're blocked. Wait 24 hours and try again. Use a second account (see https://github.com/matijse/eufy-ha-mqtt-bridge#create-a-second-eufy-account)
