### ISSUE TITLE
(node:352) UnhandledPromiseRejectionWarning: TypeError: devices is not iterable

### ISSUE THREAD

**Issue by jeremybreeschoten** [matijse/eufy-ha-mqtt-bridge#107]
Hello,

I am getting the message: 
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.24.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.3.7
 Home Assistant Supervisor: 2022.03.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:00:11] INFO: Exporting log level for nodejs: info
[23:00:11] INFO: Symlinking data dir
[23:00:11] INFO: Running 'eval' commands
[23:00:11] INFO: Generating config.yml from options.json
[23:00:12] INFO: Image build with version 0.2.24
[23:00:12] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
(node:352) UnhandledPromiseRejectionWarning: TypeError: devices is not iterable
    at EufyHttp.refreshStoredDevices (/app/eufy/http.js:45:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EufyClient.init (/app/eufy/client.js:17:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-28T21_00_15_913Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

Who can help me? Tried making second account, but cant add devices to it. I can only share it from the main account.

**Comment by VenimK** [comment]
Same problem here

**Comment by jeremybreeschoten** [comment]
Yeah I think this is not really managed or updated anymore

Op di 16 aug. 2022 08:35 schreef VenimK ***@***.***>:

**Comment by MaxWinterstein** [comment]
Yeah, was a funny ride as long as it lasted ❤️ 

But, as mentioned in README: https://github.com/matijse/eufy-ha-mqtt-bridge#warning-no-longer-actively-maintained

**Comment by mmichon** [comment]
What worked for me (based on advice from another thread this one should dupe to): 
* create a new user account (like `yourgmail+eufy2@gmail.com`
* verification emails will come to your regular `yourgmail@gmail.com`
* use that new account in your `data/config.yaml`
* restart the docker instance/service

I think the Eufy backend got more aggressive throttling so this hit us all recently. We might need to ease off on the retry code or something. I'll look at it later.
