### ISSUE TITLE
Issue after changing ISP

### ISSUE THREAD

**Issue by Brevhead** [matijse/eufy-ha-mqtt-bridge#109]
I recently changed ISP and router and by default gateway changed from 192.168.0.1 to 192.168.1.1

Since then, i've had issues with this integration, even after changing the IP address of the mqtt broker to where it correctly sits in HA.

Note that is was working correctly prior to the router change.

I run HA in a docker container in Ubuntu and the machine is connected physically to the router via Ethernet.

I have also tried deleting and adding back the Mosquitto, MTQQ and Eufy MQTT elements of the setup.

I do have a separate Eufy account with the devices shared to this and 2FA disabled.  Thats what the Eufy MQTT integration was setup to access and still is.  I have also tried unsharing and sharing again the devices.... no luck.

Logs to follow

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.24.0
 You are running the latest version of this add-on.
 System: Ubuntu 20.04.5 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2022.11.2
 Home Assistant Supervisor: 2022.10.2
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:10:31] INFO: Exporting log level for nodejs: info
[11:10:31] INFO: Symlinking data dir
[11:10:31] INFO: Running 'eval' commands
[11:10:31] INFO: Generating config.yml from options.json
[11:10:31] INFO: Image build with version 0.2.24
[11:10:31] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
(node:351) UnhandledPromiseRejectionWarning: TypeError: devices is not iterable
    at EufyHttp.refreshStoredDevices (/app/eufy/http.js:45:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EufyClient.init (/app/eufy/client.js:17:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-09T11_10_33_456Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by Brevhead** [comment]
So this turned out to be related to an issue with the way the router had been configured by the guys that installed the new network.  It was showing a non-public IP address on the router as our external one, which differed to what was shown on whatsmyip.  Once they corrected this, the add on was able to start without the errors and discover the devices.
