### ISSUE TITLE
After update from 0.7.0 to 1.0.0 the addon crash

### ISSUE THREAD

**Issue by r77s** [matijse/eufy-ha-mqtt-bridge#31]
Hi, 
I used version 0.7.0 and it works with my Eufy Cam 2c. Not I updated to 1.0.0 and now the addon crash:

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.1.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:44:52] INFO: Exporting log level for nodejs: info
[17:44:52] INFO: Symlinking data dir
[17:44:52] INFO: Generating config.yml from options.json
[17:44:53] INFO: Image build with version 0.2.0
[17:44:53] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-01-10T16:44:54.646Z"}
(node:355) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-10T16_44_55_672Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.```

I didn't change my accounts or something else."

**Comment by MaxWinterstein** [comment]
Looks like some login issue to me. 

what works best for me, use some additional accounts created only for the bridge with full admin access to all items.

**Comment by MaxWinterstein** [comment]
btw, you can wrap the log output inside three backticks, or by clicking the `<>` button when the text is marked. this will help the readability a lot :)

**Comment by gullygossner** [comment]
I am having the same problem with a previously working setup.

**Comment by matijse** [comment]
I see `100028 - Failed to request` in the error, which means your account is blocked due to logging in too often. Could be because the error in the latest 0.2.0 version made it restart often? 

If you wait a day, you should be automatically unblocked. Then try again with a new version of the Add on that uses 0.2.1...

**Comment by r77s** [comment]
I 

> Looks like some login issue to me.
> 
> what works best for me, use some additional accounts created only for the bridge with full admin access to all items.

I created a second account and use this only for the HA addon. I can login with this account in the eufy cam app on my android device.

**Comment by marcetad** [comment]
Update working for me! Thanks (Y)
