### ISSUE TITLE
Each hour sensors become unavailible

### ISSUE THREAD

**Issue by hosmancevic** [matijse/eufy-ha-mqtt-bridge#41]
Exact each hour my mqtt sensors become unavailible for a couple of seconds.

![Capturemtt](https://user-images.githubusercontent.com/25821990/107017219-24cfef00-679f-11eb-93c5-87f023bf09d3.JPG)

some examples:

Cleared (no motion detected)
9:02:28 AM - 2 hours ago
Became unavailable
9:01:57 AM - 2 hours ago
Cleared (no motion detected)
9:01:57 AM - 2 hours ago
Became unavailable
9:01:27 AM - 2 hours ago
Cleared (no motion detected)
9:01:26 AM - 2 hours ago
Became unavailable
9:00:56 AM - 2 hours ago
Cleared (no motion detected)
9:00:56 AM - 2 hours ago
Became unavailable
9:00:26 AM - 2 hours ago
Cleared (no motion detected)
9:00:26 AM - 2 hours ago
Became unavailable
8:59:52 AM - 2 hours ago
Cleared (no motion detected)
7:59:52 AM - 3 hours ago
Became unavailable
7:59:19 AM - 3 hours ago
Cleared (no motion detected)
6:59:18 AM - 4 hours ago
Became unavailable
6:58:45 AM - 4 hours ago
Cleared (no motion detected)
5:58:45 AM - 5 hours ago
Became unavailable
5:58:12 AM - 5 hours ago
Cleared (no motion detected)
4:58:12 AM - 6 hours ago
Became unavailable
4:57:39 AM - 6 hours ago
Cleared (no motion detected)
3:57:38 AM - 7 hours ago
Became unavailable
3:57:05 AM - 7 hours ago
Cleared (no motion detected)
2:57:05 AM - 8 hours ago
Became unavailable
2:56:31 AM - 8 hours ago
Cleared (no motion detected)
1:56:30 AM - 9 hours ago
Became unavailable
1:55:57 AM - 9 hours ago
Cleared (no motion detected)
12:55:57 AM - 10 hours ago
Became unavailable
12:55:26 AM - 10 hours ago
Cleared (no motion detected)
12:55:26 AM - 10 hours ago
Became unavailable
12:54:56 AM - 10 hours ago
Cleared (no motion detected)
12:54:55 AM - 10 hours ago
Became unavailable
12:54:25 AM - 10 hours ago
Cleared (no motion detected)
12:54:25 AM - 10 hours ago
Became unavailable
12:53:54 AM - 10 hours ago
Cleared (no motion detected)
12:53:54 AM - 10 hours ago
Became unavailable
12:53:24 AM - 10 hours ago
Cleared (no motion detected)
12:53:24 AM - 10 hours ago
Became unavailable
12:52:53 AM - 10 hours ago
Cleared (no motion detected)
12:52:53 AM - 10 hours ago
Became unavailable
12:52:23 AM - 10 hours ago
Cleared (no motion detected)
12:52:23 AM - 10 hours ago
Became unavailable
12:51:50 AM - 10 hours ago

**Comment by hosmancevic** [comment]
My MQTT broker logs:

1612519382: Socket error on client mqttjs_76f2a9c5, disconnecting.
1612519410: New connection from 172.**.**.* on port 1883.
[INFO] found mqtt on local database
1612519410: New client connected from 172.**.**.* as mqttjs_1e6dfcb7 (p2, c1, k60, u'mqtt').
1612520277: Saving in-memory database to /data/mosquitto.db.

**Comment by hosmancevic** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Eufy Home Assistant MQTT Bridge
 Publish events as MQTT messages
-----------------------------------------------------------
 Add-on version: 1.8.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.10  (amd64 / qemux86-64)
 Home Assistant Core: 2021.2.0
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:52:36] INFO: Exporting log level for nodejs: info
[11:52:36] INFO: Symlinking data dir
[11:52:36] INFO: Generating config.yml from options.json
[11:52:36] INFO: Image build with version 0.2.9
[11:52:36] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-02-05T10:52:38.450Z"}
info: Stored device: Doorbell (T8210P00203313C7 - type: T8210) {"timestamp":"2021-02-05T10:52:40.292Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-02-05T10:52:45.611Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-02-05T10:52:45.838Z"}
(node:361) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-05T11_52_46_352Z-debug.log
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by hosmancevic** [comment]
it looks like the addon carshed every hour and watchdog restarts the addon.

**Comment by MaxWinterstein** [comment]
Weird, email notification included more, useful information, not visible here:

```log
info: Credentials found -> reusing them... {"timestamp":"2021-02-05T10:52:45.611Z"}
info: Registered Push Token {"response":{"code":0,"msg":"Succeed."},"timestamp":"2021-02-05T10:52:45.838Z"}
(node:361) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
at Request. (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: NODE_ENV=production node --unhandled-rejections=strict index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-02-05T11_52_46_352Z-debug.log
```

Are you using some dedicated account just for the addon, or the same as e.g. your mobile phone?

**Comment by hosmancevic** [comment]
I created a separate account without 2FA for this integration.

**Comment by hosmancevic** [comment]
Strange thing is, the addon works for an hour, en then crashes..

**Comment by matijse** [comment]
I saw that too, but for me it didn't crash, but got disconnected and reconnected to the MQTT broker (not running the add-on, just the Docker image).

For example combined.log showed a lot of these:
```
{"message":"MQTT connection closed","level":"info","timestamp":"2021-02-05T11:51:19.777Z"}
{"message":"MQTT reconnect","level":"info","timestamp":"2021-02-05T11:51:20.771Z"}
{"message":"MQTT connection closed","level":"info","timestamp":"2021-02-05T12:38:23.339Z"}
{"message":"MQTT reconnect","level":"info","timestamp":"2021-02-05T12:38:24.336Z"}
{"message":"MQTT connection closed","level":"info","timestamp":"2021-02-05T12:38:24.710Z"}
{"message":"MQTT reconnect","level":"info","timestamp":"2021-02-05T12:38:25.711Z"}
{"message":"MQTT connection closed","level":"info","timestamp":"2021-02-05T12:38:27.778Z"}
{"message":"MQTT reconnect","level":"info","timestamp":"2021-02-05T12:38:28.779Z"}
```

With sometimes errors, but a lot less
```
{"error":{"errno":-104,"code":"ECONNRESET","syscall":"read"},"level":"error","message":"MQTT error","timestamp":"2021-02-05T11:30:59.220Z"}
```

I'm not sure if this is normal, because the script connects to the MQTT broker, but only transmits data once per hour... Maybe it gets disconnected due to some MQTT setting when nothing happens for some time... The script has callbacks to reconnect when that happens, so this probably happened before, but only now it is visible, due to the "last will" message I implemented. This means when it connects, it instructs the MQTT broker to send "offline" to the availability topic for Eufy devices configured in Home Assistant. When it reconnects it also sends "online", so that's why it is only very briefly Unavailable.

**Comment by hosmancevic** [comment]
Ah, that could be the issue. i am using the mosquitto broker addon for hassio and do not have the option to extend the keep alive time..

**Comment by matijse** [comment]
I was searching a bit, but I think the client is supposed to set the keepalive timeout. (I use the default 60 seconds, see https://github.com/matijse/eufy-ha-mqtt-bridge/blob/b4318648653edb913789fb71bf618e35a4710eaf/mqtt/client.js#L19) 

So I think this would mean that the MQTT library is sending a ping packet every 60 seconds (more info here: https://www.hivemq.com/blog/mqtt-essentials-part-10-alive-client-take-over/)

Maybe due to timing issues, it sometimes isn't able to send the keepalive within 60 seconds? It might be an option to increase it, so it is less likely to fail (because it has to send a ping less often)...

**Comment by matijse** [comment]
I created an update where the keepalive timeout is configurable. So you can try to see if that makes any difference...

For example, increase the timeout to 5 minutes in `config.yml` (the default is 1 minute):

```yml
mqtt:
  ...
  keepalive: 300
```

**Comment by hosmancevic** [comment]
Did not get the update yet, hope it will be there tomorrow morning so i can test!

**Comment by MaxWinterstein** [comment]
Updated Add-on is available now :)

**Comment by hosmancevic** [comment]
Thanks, i changed it to 300, will keep an eye on this.

**Comment by hosmancevic** [comment]
Looks pretty stable now, only issue i face now is after rebooting HASSIO all the Eufy sensors become unavailible, after a restart of the addod they come up again

**Comment by matijse** [comment]
Sorry for the late response... The addon should subscribe to the topic `homeassistant/status` and when a message of `online` is received, it re-initializes so Home Assistant shouldn't set them as Unavailable anymore. 

Can you confirm the message `online` is sent to the `homeassistant/status` topic when Home assistant starts?

**Comment by akeslo** [comment]
> Can you confirm the message `online` is sent to the `homeassistant/status` topic when Home assistant starts?

@matijse I am also having this issue, how do I confirm this?

**Comment by matijse** [comment]
One way is to connect to your MQTT broker with a MQTT client and subscribe to the topic `homeassistant/status` to see if the online message shows.

In the new version I'm releasing in a moment it will also log `HomeAssistant: started` when it sees this message (if the level of logging is set to "debug")
