### ISSUE TITLE
getaddrinfo EAI_AGAIN mysecurity.eufylife.com

### ISSUE THREAD

**Issue by Telmo** [matijse/eufy-ha-mqtt-bridge#53]
For some reason the container is unable to resolve the `mysecurity.eufylife.com` URL.

```
{
  "error": {
    "name": "RequestError",
    "code": "EAI_AGAIN",
    "timings": {
      "start": 1615218978584,
      "socket": 1615218978602,
      "lookup": 1615218983590,
      "error": 1615218983597,
      "phases": {
        "wait": 18,
        "dns": 4988,
        "total": 5013
      }
    }
  },
  "level": "error",
  "message": "uncaughtException: getaddrinfo EAI_AGAIN mysecurity.eufylife.com\nRequestError: getaddrinfo EAI_AGAIN mysecurity.eufylife.com\n    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:953:111)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)",
  "stack": "RequestError: getaddrinfo EAI_AGAIN mysecurity.eufylife.com\n    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:953:111)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:327:22)\n    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)\n    at TLSSocket.socketErrorListener (_http_client.js:469:9)\n    at TLSSocket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)",
  "exception": true,
  "date": "Mon Mar 08 2021 10:56:23 GMT-0500 (Eastern Standard Time)",
  "process": {
    "pid": 298,
    "uid": 0,
    "gid": 0,
    "cwd": "/app",
    "execPath": "/usr/bin/node",
    "version": "v14.16.0",
    "argv": [
      "/usr/bin/node",
      "/app/index.js"
    ],
    "memoryUsage": {
      "rss": 56905728,
      "heapTotal": 21082112,
      "heapUsed": 9201000,
      "external": 1701486,
      "arrayBuffers": 75770
    }
  },
  "os": {
    "loadavg": [
      2.63,
      2.48,
      2.48
    ],
    "uptime": 83269
  },
  "trace": [
    {
      "column": 111,
      "file": "/app/node_modules/got/dist/source/core/index.js",
      "function": null,
      "line": 953,
      "method": null,
      "native": false
    },
    {
      "column": 26,
      "file": "events.js",
      "function": "Object.onceWrapper",
      "line": 422,
      "method": "onceWrapper",
      "native": false
    },
    {
      "column": 22,
      "file": "events.js",
      "function": "ClientRequest.emit",
      "line": 327,
      "method": "emit",
      "native": false
    },
    {
      "column": 20,
      "file": "/app/node_modules/@szmarczak/http-timer/dist/source/index.js",
      "function": "ClientRequest.origin.emit",
      "line": 39,
      "method": "emit",
      "native": false
    },
    {
      "column": 9,
      "file": "_http_client.js",
      "function": "TLSSocket.socketErrorListener",
      "line": 469,
      "method": "socketErrorListener",
      "native": false
    },
    {
      "column": 20,
      "file": "events.js",
      "function": "TLSSocket.emit",
      "line": 315,
      "method": "emit",
      "native": false
    },
    {
      "column": 8,
      "file": "internal/streams/destroy.js",
      "function": "emitErrorNT",
      "line": 106,
      "method": null,
      "native": false
    },
    {
      "column": 3,
      "file": "internal/streams/destroy.js",
      "function": "emitErrorCloseNT",
      "line": 74,
      "method": null,
      "native": false
    },
    {
      "column": 21,
      "file": "internal/process/task_queues.js",
      "function": "processTicksAndRejections",
      "line": 80,
      "method": null,
      "native": false
    },
    {
      "column": 26,
      "file": "dns.js",
      "function": "GetAddrInfoReqWrap.onlookup [as oncomplete]",
      "line": 67,
      "method": "onlookup [as oncomplete]",
      "native": false
    }
  ],
  "timestamp": "2021-03-08T15:56:23.694Z"
}
```

**Comment by matijse** [comment]
Hmm weird, haven't seen this before. Is this still an issue? Seems like the thing that can magically disappear with a reboot / wait some time ;)

**Comment by riversideneyon** [comment]
I have same problem. After some time days it seems not able to resolve.
Starting the addon again resolve the issue. But the issue come back again after some days

**Comment by matijse** [comment]
I think with the current code when a request fails, it throws an exception and the whole script crashes. So there is no retry.

The script only contacts the Eufy server once every hour, to update the battery values. It also keeps a connection with Google/Firebase for push messages, but that is handled by a library, which maybe does some form of reconnecting on error. 

So if your internet is down this might be an issue for the push connection and for the Eufy connection only on the moment it is trying to update the battery percentage values.

**Comment by czbird77** [comment]
It's still an issue :-(
