### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by vlumikero** [matijse/eufy-ha-mqtt-bridge#54]
I'm getting the following as of a couple of days. The error occurs immediately at startup. Any ideas?

```
[16:15:25] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-03-17T15:15:30.376Z"}
(node:356) UnhandledPromiseRejectionWarning: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.
    at /app/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-17T15_15_31_476Z-debug.log
```

**Comment by vlumikero** [comment]
Is this an issue in the eufy-node-client?

**Comment by matijse** [comment]
This is an error reported by Eufy when logging in: `Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.`

This means you got blocked by Eufy, for logging in too often, or using the wrong password too often. If you needed to restart the container or it auto-restarted too many times this happens. Wait 24 hours and try again.

Also see the readme: https://github.com/matijse/eufy-ha-mqtt-bridge#create-a-second-eufy-account You should not use the same account you use in the app, because they will lock each other out.

**Comment by vlumikero** [comment]
I have verified that the account works now, but I’m getting this instead:

```
UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:355)
