### ISSUE TITLE
HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by vlumikero** [matijse/eufy-ha-mqtt-bridge#56]
I’m getting the following error after a while of operation. Any ideas?

```
UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.

**Comment by matijse** [comment]
Do you use the same account on the app and this integration? It seems if you log in on multiple locations, you get logged out on the other locations...

**Comment by vlumikero** [comment]
No, I use separate accounts.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vlumikero** [comment]
It seems to be related to MQTT. I'm using the HA official MQTT addon, and I can't really see why a connection would be refused there. Any ideas?

```
{"message":"MQTT reconnect","level":"info","timestamp":"2021-01-22T06:27:27.635Z"}
{"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.101","port":1883},"level":"error","message":"MQTT error","timestamp":"2021-01-22T06:27:27.683Z"}
{"message":"MQTT connection closed","level":"info","timestamp":"2021-01-22T06:27:27.698Z"}

**Comment by vlumikero** [comment]
The MQTT log shows the following:

```
1617099772: New client connected from 172.x.x.x as mqttjs_xxxxxx (p2, c1, k60, u'xxxxxxx').
1617099778: Socket error on client mqttjs_xxxxxx, disconnecting.

**Comment by MaxWinterstein** [comment]
> The MQTT log shows the below (the xxxxx are redactions). 172.x.x.x is my external IP address, and I don't understand why that shows up here.
> 
> ```
> 1617099772: New client connected from 172.x.x.x as mqttjs_xxxxxx (p2, c1, k60, u'xxxxxxx').
> 1617099778: Socket error on client mqttjs_xxxxxx, disconnecting.
> ```

You're sure this is your public address? I would guess it is `172.30.32.1` - which is some reserved private, and as far as i remember the gateway address for supervisor installed addons.
See https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses

**Comment by matijse** [comment]
Docker uses 172.x.x.x addresses, so it is probably the IP of the container.

The MQTT connection closes quickly, but it does connect. I think MQTT is not the issue. Since your original error message shows a 401 error (on a HTTP request), I think the MQTT connection works, but is quickly stopped because the whole script crashes due to the HTTP connection error.

Can you show a longer part of the log, to see where the 401 error comes from?

**Comment by vlumikero** [comment]
@matijse 
Here's the log from the bridge:
```
[12:22:38] INFO: starting original stuff...
> eufy-ha-mqtt-bridge@1.0.0 start /app
> NODE_ENV=production node --unhandled-rejections=strict index.js
info: Migrating the database... {"timestamp":"2021-03-30T10:22:46.811Z"}
info: Stored device: Doorbell (T8200N0019393C7B - type: T8200) {"timestamp":"2021-03-30T10:22:49.866Z"}
info: Credentials found -> reusing them... {"timestamp":"2021-03-30T10:22:57.591Z"}
(node:355) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eufy-ha-mqtt-bridge@1.0.0 start: `NODE_ENV=production node --unhandled-rejections=strict index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eufy-ha-mqtt-bridge@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-30T10_22_58_581Z-debug.log

```
And this is from the exceptions.log:

```
{"error":{"name":"HTTPError","timings":{"start":1615053281380,"socket":1615053281386,"lookup":1615053281388,"connect":1615053281419,"secureConnect":1615053281453,"upload":1615053281454,"response":1615053281487,"end":1615053281491,"phases":{"wait":6,"dns":2,"tcp":31,"tls":34,"request":1,"firstByte":33,"download":4,"total":111}}},"level":"error","message":"uncaughtException: Response code 401 (Unauthorized)\n
HTTPError: Response code 401 (Unauthorized)\n
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n
    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"HTTPError: Response code 401 (Unauthorized)\n
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n
    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Sat Mar 06 2021 18:54:41 GMT+0100 (Central European Standard Time)","process":{"pid":358,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/bin/node","version":"v14.15.4","argv":["/usr/bin/node","/app/index.js"],"memoryUsage":{"rss":35831808,"heapTotal":11579392,"heapUsed":10625772,"external":2255679,"arrayBuffers":615304}},"os":{"loadavg":[1.24,1.14,0.92],"uptime":1033079},"trace":[{"column":42,"file":"/app/node_modules/got/dist/source/as-promise/index.js","function":null,"line":117,"method":null,"native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false}],"timestamp":"2021-03-06T17:54:41.695Z"}

**Comment by vlumikero** [comment]
@matijse the secondary account is indeed a guest account. I’ll change it and see if it makes a difference.

**Comment by vlumikero** [comment]
I did try removing the credentials, that did not help.

Addon log, using debug log level:
```
debug: ---- EUFY INITIALIZE DONE! ---- {"timestamp":"2021-03-30T21:54:43.903Z"}
debug: Received push message {"pushMessage":{"id":"xxxx","from":"xxxx","to":"xxxx-xxxxxx","category":"com.oceanwing.battery.cam","persistentId":"0:xxxx","ttl":3600,"sent":"1617141903242","payload":{"google.c.sender.id":"xxxx","doorbell":"{\"event_type\":3100,\"event_time\":1617141902682,\"event_session\":\"\",\"pic_url\":\"\",\"video_url\":\"\",\"title\":\"\",\"content\":\"\",\"url\":\"\",\"url_ex\":\"\",\"campaign_name\":\"\",\"user_id\":\"xxxx\",\"device_sn\":\"T8200N00xxxx\",\"monitor_id\":0,\"create_time\":1617141903233,\"file_path\":\"\",\"cipher\":0,\"channel\":0,\"outer_title\":\"\",\"outer_body\":\"\"}"}},"timestamp":"2021-03-30T22:05:03.350Z"}
debug: Notification with unknown type {"id":"062EF4A0","from":"348804314802","to":"xxxx-xxxx","category":"com.oceanwing.battery.cam","persistentId":"0:xxxx","ttl":3600,"sent":"1617141903242","payload":{"google.c.sender.id":"xxxx","doorbell":{"event_type":3100,"event_time":1617141902682,"event_session":"","pic_url":"","video_url":"","title":"","content":"","url":"","url_ex":"","campaign_name":"","user_id":"xxxx","device_sn":"T8200Nxxxx","monitor_id":0,"create_time":1617141903233,"file_path":"","cipher":0,"channel":0,"outer_title":"","outer_body":""},"payload":{"event_type":3100,"event_time":1617141902682,"event_session":"","pic_url":"","video_url":"","title":"","content":"","url":"","url_ex":"","campaign_name":"","user_id":"xxxx","device_sn":"T8200Nxxxx","monitor_id":0,"create_time":1617141903233,"file_path":"","cipher":0,"channel":0,"outer_title":"","outer_body":""}},"timestamp":"2021-03-30T22:05:03.355Z"}
debug: Refreshing devices... {"timestamp":"2021-03-30T22:54:43.903Z"}
(node:355) UnhandledPromiseRejectionWarning: HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
Exceptions.log contains a lot of this:
```
{"error":{"name":"HTTPError","timings":{"start":1615064303557,"socket":1615064303562,"lookup":1615064303568,"connect":1615064303602,"secureConnect":1615064303690,"upload":1615064303692,"response":1615064303726,"end":1615064303733,"phases":{"wait":5,"dns":6,"tcp":34,"tls":88,"request":2,"firstByte":34,"download":7,"total":176}}},"level":"error","message":"uncaughtException: Response code 401 (Unauthorized)\nHTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","stack":"HTTPError: Response code 401 (Unauthorized)\n    at Request.<anonymous> (/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","exception":true,"date":"Sat Mar 06 2021 21:58:23 GMT+0100 (Central European Standard Time)","process":{"pid":358,"uid":0,"gid":0,"cwd":"/app","execPath":"/usr/bin/node","version":"v14.15.4","argv":["/usr/bin/node","/app/index.js"],"memoryUsage":{"rss":31768576,"heapTotal":11579392,"heapUsed":10844692,"external":2281634,"arrayBuffers":641259}},"os":{"loadavg":[0.54,0.9,0.94],"uptime":1044101},"trace":[{"column":42,"file":"/app/node_modules/got/dist/source/as-promise/index.js","function":null,"line":117,"method":null,"native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":93,"method":null,"native":false}],"timestamp":"2021-03-06T20:58:23.945Z"}

```

Combined.log:
```
{"pushMessage":{"id":"24CDF852","from":"xxxx","to":"xxxx","category":"com.oceanwing.battery.cam","persistentId":"0:xxxx","ttl":3600,"sent":"1615066216163","payload":{"google.c.sender.id":"xxxx","doorbell":"{\"event_type\":3100,\"event_time\":1615066215503,\"event_session\":\"\",\"pic_url\":\"\",\"video_url\":\"\",\"title\":\"\",\"content\":\"\",\"url\":\"\",\"url_ex\":\"\",\"campaign_name\":\"\",\"user_id\":\"xxxx\",\"device_sn\":\"T8200N00xxxx\",\"monitor_id\":0,\"create_time\":1615066216154,\"file_path\":\"\",\"cipher\":0,\"channel\":0,\"outer_title\":\"\",\"outer_body\":\"\"}"}},"level":"debug","message":"Received push message","timestamp":"2021-03-06T21:30:16.271Z"}
{"id":"24CDF852","from":"xxxx","to":"xxxx","category":"com.oceanwing.battery.cam","persistentId":"0:xxxx","ttl":3600,"sent":"1615066216163","payload":{"google.c.sender.id":"xxxx","doorbell":{"event_type":3100,"event_time":1615066215503,"event_session":"","pic_url":"","video_url":"","title":"","content":"","url":"","url_ex":"","campaign_name":"","user_id":"xxxx","device_sn":"T8200Nxxxx","monitor_id":0,"create_time":1615066216154,"file_path":"","cipher":0,"channel":0,"outer_title":"","outer_body":""},"payload":{"event_type":3100,"event_time":1615066215503,"event_session":"","pic_url":"","video_url":"","title":"","content":"","url":"","url_ex":"","campaign_name":"","user_id":"xxxx","device_sn":"T8200Nxxxx","monitor_id":0,"create_time":1615066216154,"file_path":"","cipher":0,"channel":0,"outer_title":"","outer_body":""}},"level":"debug","message":"Notification with unknown type","timestamp":"2021-03-06T21:30:16.273Z"}

```

**Comment by vlumikero** [comment]
The MQTT log says:
```

1617810471: New client connected from 172.30.32.1 as mqttjs_d68546ee (p2, c1, k60, u'xxxx').

1617814080: Socket error on client mqttjs_d68546ee, disconnecting.

```

The bridge was working for an hour, then this socket error and disconnect. I’ve been trying to read up on the disconnect issue but no luck so far. Both the bridge and the mqtt addons are running on the same RPI so it seems unlikely to be a network issue.

Any ideas?

**Comment by matijse** [comment]
The error occurs right after "Refreshing devices..." This happens every hour (to update the battery percentages). This is also the reason the MQTT client disconnects (with a socket error) after an hour. Due to the error, the script crashes and does an unclean disconnect with the MQTT server.

So I don't think there's an error with your MQTT setup. The issue is that for some reason you get a 401 Unauthorized error when getting the device list after one hour. The device list is also retrieved on startup, and that works fine it seems.

The 401 error means your authentication token is no longer valid, while normally they are valid for a month I believe. Are you sure the account credentials you use for the addon are not used in any other script or phone app? And there is no way the addon can run twice by accident or something?

I have no clue where to search it otherwise...

**Comment by matijse** [comment]
In the next release I've added some more logging to the Eufy HTTP requests, so it shows which call exactly fails. Also it shouldn't crash the entire script anymore when a HTTP call fails.

**Comment by vlumikero** [comment]
I reinstalled both the MQTT addon as well as the eufy-ha-mqtt-bridge a couple of times, and manually deleted (renamed) the share/eufy-ha-mqtt-bridge directory, and now it seems to work better. The bridge has been running for 12+ hours.

It doesn't seem to recreate the share/eufy-ha-mqtt-bridge directory though. Are the logs now stored elsewhere?

**Comment by MaxWinterstein** [comment]
> It doesn't seem to recreate the share/eufy-ha-mqtt-bridge directory though. Are the logs now stored elsewhere?

Yeah, this has been 'unified' to behave like all other addons. See [Changelog](https://github.com/MaxWinterstein/homeassistant-addons/blob/main/eufy-ha-mqtt-bridge/CHANGELOG.md#1120---2021-03-06)

There is also some documentation on how to restore that behavoiur if it is needed, e.g. to export data:
https://github.com/MaxWinterstein/homeassistant-addons/blob/main/eufy-ha-mqtt-bridge/DOCS.md#configuration
